### ISSUE TITLE
containerise config

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#10]
funny seeing you also using this extension :)

I really like this and the way I would like it to work is to open specific sites in a container (this works), but also when I click on a link within the container that points to another website, I want it to jump out of that container OR load in the proper container if the link is configured to be in a specific container.

I found one comment on the reviews of this extensions that i found really interesting and it almost get's it working the way I want.

https://addons.mozilla.org/en-US/firefox/addon/containerise/reviews/1590636/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org
"You can assign a container to specified website(Which multi account container still CAN'T). So your container changes when a website does not assigned it. To do that enable "Match domain only" and "Default container" option in addon's setting. You can use this rule "!sitedomain.*"(without quotation) assign any site to container. Example if we assign google's domain to google domain we should assign "!google.*" rule to Google container."

with this config all unconfigured urls get loaded into the "default container", but I (think I) would prefer to load those links into no container (for easier management). 

Anyways, give it a try and let me know what you think :)

update: forgot to mention this is without temp containers / multi account containers extension

**Comment by crssi** [comment]
Hi @bitpixl, thank you for making a suggestion.

With upper recipe would you mind to do one config and a few URL tests.
Complete steps:
1. Take a clean FF profile (just in case), install `Containerise` and enable `Match domain only` and `Default container` option in addon's setting
2. Assign the rules: `!google. , GOOGLE` and `t.co , TWITTER`
3. Visit the following URLs and observe the outcome: `google.com.domain.com`, `google.com.test.com`

What happens:
The first URL opens in GOOGLE container, when it should actually open in default container.
The second URL opens in TWITTER container, when it should actually open in default container.

Let me know if yours observing matches mine.

Cheers

**Comment by bitpixl** [comment]
Hi @crssi ,

did some testing and this is what I noticed:
1. `!google. , GOOGLE`
2. `t.co , TWITTER` (notice you wrote without the '!')

test urls: `google.com.domain.com`, `google.com.test.com`

results: 
`google.com.domain.com` does indeed load in GOOGLE container.
`google.com.test.com` however jumps to default container (however with !t.co it does as you wrote, open in TWITTER).

once I changed the google rule to 
`!*.google.* , GOOGLE`
`google.com.domain.com` loaded in the default container as well and google.com still loaded in GOOGLE container.

**Comment by crssi** [comment]
What about `www.google.com.domain.com` ?

**Comment by crssi** [comment]
I have to get back to the drawing board and rethink. 😄

**Comment by bitpixl** [comment]
I was checking out the containerise github and found this topic:
https://github.com/kintesh/containerise/issues/106

So I turned off "match domain only" and set default container to "No Container" and now it seems to do what I want. 
- Loading the sites that I configured to be in a container load in that container
- Selecting an link within one of those containers that points to an url that isn't configured to be in a container, load in the 'non container/normal enviroment' 👍 

I still have questions, like how can I (for example) run two speperate google containers at the same time? (work/personal)
The documentation seems to be a sore point for this extension.

And I can also see potential issues, like a shopping site in a container, then having to pay, thus loading that payment bit in the non container (or maybe a seperate container)... probably breaking the process?

(I probably also have to spend some time trying to understand regex...)

anyways I'll keep digging for a bit

edit:

I'm also wondering what your container strategy is, for every site that you login you create a seperate container?
or do you use "subject containers" like "shopping" "tech", etc?
and then for all other browsing stuff use a temp container?

What strategy do you use for family/friends that are non technical?

Just wondering :)

**Comment by crssi** [comment]
The strategy/idea is simple (but harder to implement).

Every URL entry or spawn from search site should start in its own container, which must be destroyed after use... that way we get rid of every kind of tracking.
Left click on a search sites like DDG and G should open a new tab/container.
Otherwise (out of search engine site) the left mouse click must never leave the container to avoid logins and such breakages.
The middle mouse click follows url in a new tab... if the domain is the same then it goes to the same container as the source is, otherwise it open a new tab in a new container.

For all of that the TC is the main engine.

Then we have Containerise, which is used for session permanent containers, to avoid constant entering credentials.
In my case I am using also rules like `*.github.com , GITHUB`, `*.gitlab.com , GITLAB`... etc.

The G is a special case... unfortunately we have to have a session permanent container to limit the G nagging, otherwise the family staff would get nuts.
That comes also with a drawback, which you have mentioned with `like how can I (for example) run two speperate google containers at the same time`. I guess you can't... not in this scenario. 😞 
But... I guess, even when you would use different containers in that case, the G already know that those two (or many) accounts are tight to the same person and avoiding such would actually not bring any benefit.
More important for me is that G doesn't follow the user on other sites by some tracking cookies or other client side technique, and this is accomplished by TC auto container (see at the top of this post... `Every URL entry or spawn from search site should start in its own container`) and other methods like Smart Referer and PooP.

Additionally when using auto mode TC we can also afford to accept cookie standard ETP (with accepting some 3rd party cookie) and avoid breakages.

I have updated the Containerise rules now.

Let me know what you think... I like this brainstorming.
