### ISSUE TITLE
A few questions about how you use containers

### ISSUE THREAD

**Issue by sanjayen** [crssi/Firefox#11]
Thank you for creating user-overrides.js and maintaining it as well as other config files. I have struggled to parse arkenfox.js line-by-line. Your config makes it a convenient starting point.

I had a few questions about how you use containers with these addons.

1. The containerrise.txt file contains only a few domains for the respective container. Do you add the other domains, for each of these companies, to make the container robust?

2. How does Containerrise behave, if a page loaded within one container, has a URL that belongs to a different container?

3. Temporary Containers keeps on adding names of different containers. How can I add them back to the Containerrise config?

4. Temporary Containers do not load earlier tabs when the session is restarted. How do you work around such a problem, when TC is set to automatic?

Thank you for the work that you do.

**Comment by crssi** [comment]
Thank you for your interest. 😄 

With `Containerise` you can force domains to open withing specific container which stays permanent over a session.
So you will achieve two things... one is to keep login cookies over a session not needing to sign in everytime and the second you will keep those domain forcibly separated from other domains.

1. `Containerise.txt` is just a stater or sample... surely we can add other domains, but those works for me ATM.. but if you have suggestions, I am open to it. 😉 Also I add every domain into that I am using continuously to avoid login again and again... for example `*.github.com , GITHUB` and `*.gitlab.com , GITLAB`... those are not in the `Containarise.txt` due to a privacy reason.
2. It should kick-in when TC Automode kicks in. So at new page load.
3. Containerise config is managed separately for each individual differently. I have abot 10 additional lines to the `Containerise.txt` in the config.
4. Does not? I have not find any problems or maybe I don't understand a question.. would you ming to let me know the steps to reproduce, please.

If you have any suggestions or anything else, please, do not hesitate to let me know... I am open to discussions. 😉 

Bear in mind that I am not a native speaker, so some confusions might play fun with us.

Cheers

**Comment by sanjayen** [comment]
Thank you for your reply.

Not a problem that you are not a native speaker. I will have to do a better job to explain myself clearly and that is useful to me.

Answering to each point;

1. I went through all the source code, and hence domains, for most of the official/ unofficial containers (e.g. Firefox container, Google with Integration container etc.) available on AMO. Does it make sense to compile them and share with you?

2. I do not think I explained myself well enough. This is a hypothetical scenario - if I open twitter.com, the container for twitter will kick in. Let's say twitter.com makes multiple calls to facebook.com (which has its own different container). I am guessing even facebook.com will load within the same twitter container, as it is within the scope of the container. So Facebook, in this case, be able to read that twitter was the referrer as they both belong in the same container.

3. Understood that some of the URLs/ containers may be personal choice

4. I used your TC config which enables automatic mode. And the URLs started opening in TC containers. I had to restart my Firefox nightly due to an update. I have session restore enabled. When Firefox restarted, all the TC tabs were gone.

Also, along with disabling Firefox history and cache, does it make sense to use Cookie AutoDelete when sites are opened in No Container?

**Comment by crssi** [comment]
1. Sure it does... every improvement might be great.
2. That is true, but I rely to RFP (resist finger printing) in dFPI (dynamic first party isolation) not to cross share cookies and there are also Firefox ETP (enhanced tracking protection) and referer manipulation and PooP extension and uBO filter to block a lot of tracking URLs.
3. I am using it for those few sites I am using frequently to avoid constant logins... to simplify logins I am using firefox password sync.
4. That should not happen... can you replicate with going to `about:profiles` and select `Restart normally...`? Can you replicate with official release and not nightly?

> Also, along with disabling Firefox history and cache, does it make sense to use Cookie AutoDelete when sites are opened in No Container?

The plan is that no site should open in `No Container`, so everything is always contained, but if something slips trough, then session restart should clean up all the garbage. To today I haven't found any leaks.
Draw back is that after every session start we need to re-login to our favorites, but I do a session restart few days and not multiple times per day, so that is not a problem, at least not for me.
So `Cookie AutoDelete` makes no sense then... I was using it in the past, but back then Firefox was not as advanced as it is today.

**Comment by sanjayen** [comment]
Thank you for your reply.

Let me work on compiling the domains vs container list and share with you.

Agree with your approach. I am just starting out with containers as I always found it to be overwhelming. With your config, I can understand how best to configure it.

Will ask some more questions in the coming days. Want to use containers, just like you, all the time.

**Comment by crssi** [comment]
Off topic... to explain "my" model of TC usage.
1. Every tab must open in a container.
2. Everything left or middle clicked on a search engine result page (like DDG or google or bing) must open in a new tab new container
3. Left mouse click should follow the link and stay within the same container, except if it is defined in a Containerise
4. Middle mouse click must follow the link  to a new tab and new container, except when link follows the same domain/subdomain

Left click is safe to use in login pages that are redirected outside the current domain, so are the payments too, like paypal or such.
Middle click is your privacy friend, since it forces to open a new tab new container... except if the destination is the same domain/subdomain as the current/source domain is.

Also, selecting the link with the right click and choosing to open in the "No Contaner" should open in a new tab and new contaner.

**Comment by sanjayen** [comment]
This is a great model.

I have to start using middle clicks more often. I use left click and open in new tab as my default clicking behaviour.

**Comment by crssi** [comment]
@sanjayen can I close this issue or do you have any additional questions/suggestions?

Cheers

**Comment by sanjayen** [comment]
Closing this issue.

I did not get time to create the container list and share with you. Will create a new issue when I compile it.

Thank you for your config. I have been using containerise along with the rules and it works well.

**Comment by crssi** [comment]
I am glad that you find the "config" helpful.

Wish you best 😄
