### ISSUE TITLE
NeatURL gone?

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#3]
Hi CRSSI,

hope all is well these days.
I still pop in from time to check your firefox config and noticed your neat url config is gone.
Probably has something to do with the latest updates. Do you still use NeatURL?

**Comment by crssi** [comment]
All well here, thank you and I wish you are well too.

You know what, I am totally undecided about NeatURL.
1. I have obviously hit a sweet spot with uBO and uM filters, since I have almost 0 (zero) interference by NeatURL, except for UTM and some unimportants.
2. I don't like the latest update.
3. ClearURL is getting mature and approved by mozilla

^^ This is why I have decided to try swap from NeatURL to ClearURL and see what happens.
What I do not like about ClearURL is that is not configurable and if something is wrong there is only option to temporarily disable it. But in the last 2-3 weeks I haven't have any such breakage.

Maybe I am wrong, maybe I am not, i really don't know.
What is your opinion?

**Comment by crssi** [comment]
Uh, forgot to mention... ETags are ATM dealt with ClearURL.

**Comment by bitpixl** [comment]
I'm not using uM as it's too much micro management for me and others I help out, but I know it's needed if you want full protection.

From what I've read/understand, I've got etags under control by using `"browser.cache.memory.enable", false` and `browser.cache.memory.capacity", 0` as [tested by you](https://github.com/ghacksuserjs/ghacks-user.js/issues/179#issuecomment-348952233) a while ago ;)

From what I've seen with the new NeatURL it compares the default list to the custom added ones and then removes any matching entries from the custom config if it already exists in the default list. I'll have a look at ClearURL, zero management is always something I'm aiming for ;)

(update: I don't like that ClearURL asks for more permissions)
(update1: but that's explained [here](https://gitlab.com/KevinRoebert/ClearUrls/-/issues/159))

**Comment by bitpixl** [comment]
Trying out ClearURLs atm and after seeing the tray icon, I tried this addon out in the past.
I tried accessing rarbg.to, but I got stuck in a loop (made an exclusion for that in NeatURL, so I knew it was a proper test) Seems like I'm not the only one having an issue on that site as there's already an open ticket. Let's see how fast the developer response is ;)

**Comment by crssi** [comment]
Hmmm... tried `rarbg.to`, but here it is opening OK.

**Comment by bitpixl** [comment]
Problems start when you start browsing the site and / or select a download.
Then threat_defense starts acting up. I do access the page using a vpn.

[here's the link](https://gitlab.com/KevinRoebert/ClearUrls/-/issues/505) to the open ticket.

**Comment by crssi** [comment]
I see it now... this exactly is a case why my move is wrong. Thank you for bringing it on.
If something goes wrong you can't do nothing about, just to report and hope for fast resolution and mercy.

Also, from my experience, I don't see how `language` and `cid` would bring more privacy?
If you ask me, I would ditch those two rules out.

I have also posts there now and will see how fast the resolution will be... otherwise going back to NeatURL.

**Comment by bitpixl** [comment]
I think being able to modify the rules is to valuable, so probably better to go back to NeatURL and wait until maybe ClearURLs implements it as well. I did see a request for it as well.

**Comment by bitpixl** [comment]
Woop spotted your spring cleaning NeatURL update! Never copied/pasted something that quick before ;)

**Comment by crssi** [comment]
lol... actually spring cleaning was mostly for uBO filter lists and config revamp and moving away from uM.

I still have to dig into NeatURL specifics.
As said, I do not like the new update and forcing the default config.

**Comment by bitpixl** [comment]
Thanks for the update @crssi , closing the ticket and keeping an eye on your page in the future ;)

**Comment by crssi** [comment]
Thanks @bitpixl 
I think this will be it for now. If you find something odd, let me know.

Cheers
