### ISSUE TITLE
 userChrome.css removes the entry open in new tab from the context menu

### ISSUE THREAD

**Issue by tzipx5** [crssi/Firefox#4]
https://pictshare.net/ff2jlw.jpg
https://pictshare.net/eirko3.jpg

is that what you want? If so, how can I restore the entry?
can i use firefox without the userChrome.css or would this change the canvas fingerprint?

ps. 
what function does the link to your profile in the user-overrides.js have?
Is this just for your personal backup and as an example?

Greetings and thanks for making firefox safer and privacy friendly.

**Comment by crssi** [comment]
Thank you for bringing up the attention.

If I remember correctly... In the past, this context menu didn't work as intended with containers and just brought the confusion. So, actually this is intended or it was intended back then, but not needed anymore.
I have tested it now and its much better, it just misses (not critical) when the target is the same permanent container.
I have removed/commented now from userChrome.css. See: https://github.com/crssi/Firefox/commit/3da2036a03fe01da0c7adbe853b61343cbfa0a58

Otherwise userChrome.css was made created initially for two reasons.
1. to remove options to private browsing, since the PB doesn't bring more protection but less in my case... at least back in time there was no option to run extensions in PB mode
2. to colorize Urlbar when being on a site without TLS/SSL for better awareness

Beside upper two points the userChrome.css and userContent.css does not bring anymore to privacy/security but some cosmetic changes to UX, which I prefer more.

> what function does the link to your profile in the user-overrides.js have?

I am not sure what you meant with... can you be more specific which line?

Thank you and cheers

**Comment by tzipx5** [comment]
hi and thanks for the detailed explanation, now things are getting clearer. 

i have already looked at some other overrides and find it a lil bit confusing that you have a download link from your Profil (i mean the Profile.zip file) in your override. 
Your profile should not be used and i should use my own profile, right?

What else I am interested to know which settings you made in https://github.com/gorhill/uBlock/wiki/Advanced-user-features and why? 

with your 884.214 network filters ＋ 142.488 cosmetic filters oO of which you have built them into your ublock build i don't need uMatrix anymore. Awesome...
Your override and addon concept seems to me to be a good compromise between privacy and compatibility. I will continue to follow it closely. 

Thank you for your attention and Enjoy your week.

**Comment by crssi** [comment]
> Your profile should not be used and i should use my own profile, right?

Oh. I see. Will remove that link from overrides to avoid confusion.
I have this profile to distribute easily to other computers.
It is clean, done by "my" template and anyone can use it.
The problem I have with it is that when I bring it to a new computer, sometimes the extensions does not start.
So I need to disable all extension restart firefox and enable them back.
This is a behavior I haven't seem before a few versions of FF back and I haven't have time to investigate yet.
Maybe it has something to do with the extensions update.

You have there also a [firefox-update.ps1](https://github.com/crssi/Firefox/blob/master/firefox-update.ps1), which helps you deliver Profile.zip to your computer.
Just copy paste to your powershell.
It copies the profile.zip, backups your old profile into zip, replaces your old profile with new one and copies the bookmarks, passwords, etc from your old profile into a new one.

I will answer to other questions in the posts that follow.

**Comment by crssi** [comment]
> with your 884.214 network filters ＋ 142.488 cosmetic filters oO of which you have built them into your ublock build i don't need uMatrix anymore

Until recent changes I have used both, uBO and uM, where separated a security/phishing/mailware section to uM and ads,tracking,cosmetics... to uBO. So if uM did the block, then it was a sign not to go further.
I like this approach, but it has a downside. If, for example my mother calls me about a breakage, I cannot do a thing remotely to resolve the problem when it is the uM asset in question.

I believe there are too many network filters or some hostfilter list could easily be removed... but due to lack of detail blockage statistics it is very hard to find which list actually never kicks in.
And also everyone's browsing behavior is different... this is a great example, why Mozilla (or any SW vendor) really needs telemetry (which should be anonymized of course).

**Comment by crssi** [comment]
> What else I am interested to know which settings you made in https://github.com/gorhill/uBlock/wiki/Advanced-user-features and why?

OK. Advanced features enables you control the dashboard and enables dynamic filtering.
One part consist of the following rules https://github.com/ghacksuserjs/ghacks-user.js/issues/319#issuecomment-364119775 but the whole issue is good to read.
We also need the some exclusions since we are using LocalCDN (replacing Decentaleyes), which deals with those.

I think I have answered all questions.
If I have missed something out or need more clarification, do not hesitate to ask.

Thank you and cheers

**Comment by crssi** [comment]
I am sorry, but I have disable it back, since it brings a confusion.
But, at least you know which line to remove. You can also fork it and remove it for good at your repository.

But here is the solution with Temporary Containers (Options -> Advanced -> General ->Context Menu... check the first entry).
![alt text](https://i.imgur.com/RRJftpDl.png)

Cheers
