### ISSUE TITLE
iCloud, Smart Referer and XOrigin settings...

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#5]
Hi Crssi,

hope you don't mind me asking you for help.
I'm trying to get icloud working, but I just can't seem to get the logon prompt to appear.

I'm using (and enjoying) the latest Firefox ESR 68.9.0 and also using the ghacks 68 user.js version.
I've read the icloud tickets on ghacks and my setup looks like this (while still not working):

clean profile
user.js (68 version) added
changed "network.http.referer.XOriginPolicy" to "0"
added smart referer addon
added following (icloud) rules to smart referer (based on own testing and your whitelist)
```
*.apple.com - *.*apple*.com
*.icloud.com - *.*apple*.com
```
other smart referer settings:
- default whitelist enabled
- send URL you're going to as referer (recommended)
- Lax

I also tried the default whitelist off / strict mode.

In the browser console I see that all referers are taken care off, none appear, but still icloud doesn't show the logon screen. Are you experiencing the same issue atm?

Also if I set XOriginPolicy to "0" and don't install smart referer, it should also just work right (with the downside that referers are fully send ofc). Just wondering what I'm doing wrong...

**Comment by crssi** [comment]
Of course I don't mind. 😄 
Its RFP, which is a root cause.

The Mozilla can't decide if its a Firefox bug, Apple bug or both, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1621729

I would suggest you using another browser for iCloud.
Maybe you could try something like https://addons.mozilla.org/firefox/addon/toggle-resist-fingerprinting/, but you must know that FPI is global and not per site/tab.

Cheers

**Comment by bitpixl** [comment]
ahh ok.... should have known it's RFP...and that's staying on for sure!
Well, as long there's people looking into it, I'll just wait and see.

Thanks Crssi, saved me alot of headache!
