### ISSUE TITLE
URLhaus blocklist is not enable by default in my-ublock-backup.txt

### ISSUE THREAD

**Issue by tzipx5** [crssi/Firefox#7]
Hi, today i have check your firefox ublock-backup and would like to draw your attention to some changes.

Check
https://github.com/gorhill/uBlock/releases/tag/1.28.2
https://github.com/uBlockOrigin/uBlock-issues/issues/1116
https://github.com/uBlockOrigin/uBlock-issues/issues/984

Cheers

**Comment by crssi** [comment]
Hey, thank you.

I think I did a change in the last days and since I am on vacation without some good access to Internet I haven't have possibility to push a commit yet.

Did now, could you check if its OK and report me back, pretttyyy please. 😄

I came online in an area that have at least mediocre access to make a push and to write this message. 😉 

Cheers

**Comment by tzipx5** [comment]
Okay, i checked fresh backup and now its enable.
Please enjoy your vacation and stay offline.
There is nothing that can't wait 2-3 weeks.
Only Peanuts  😄

i use your backup with uBo medium mode https://github.com/gorhill/ublock/wiki/Blocking-mode:-medium-mode 
and it works flawlessly.

Cheers

**Comment by crssi** [comment]
Thank you for confirmation.

I do not favor uBO medium mode, since I think its better to use a blocklist.
See the blocklist https://github.com/crssi/Firefox/blob/master/.Archive/uBO-3rdPartyIFrame.txt for 3rd party `frame/subdocument`.
See the blocklist https://github.com/crssi/Firefox/blob/master/.Archive/uBO-3rdPartyScript.txt for 3rd party `script`.
See the blocklist https://github.com/crssi/Firefox/blob/master/.Archive/uBO-3rdPartyXHR.txt for 3rd party `xhr`.

The first line in each denies globally and the we have allowances, but precise and specific and not for whole domain.

If I have not written clearly, just ask... I am not native English speaker. 😉
