### ISSUE TITLE
?_Neat Url archived?

### ISSUE THREAD

**Issue by bitpixl** [crssi/Firefox#9]
Hi Crssi,

just wondering what made you archive your neat url config?
Have you stopped using it?

Cheers!

**Comment by crssi** [comment]
Yes. That is true.
ClearURLs rules evolved in a quality in all this time, where NeatURL has a slight change in config, which I don't like.
But... I still don't like ClearURLs too much, since I don't feel to have good user control in case if breakage happen (which didn't for me in the last 2 months of use... so this is good).

Anyway... it looks that I have got a sweet spot of uBO config and rules collection where such extensions kick-in extremely rare.

OT: ATM I am revamping everything in the last 2 months to be prepared for a few days after FF82.

Cheers

**Comment by bitpixl** [comment]
Sorry to hear that, I really liked your extra config on Neat URL, but it is what it is ;)
What would you recommend for a novice? Stick with NeatURL or also hop over to ClearURLS? 

As always I value your opinion 👍

**Comment by crssi** [comment]
Thank you

You can still stick with NeatURL... that is why it is archived and not removed.
But, as said, neither of those really kick-in a lot those days.
I have find out that **mostly** directly correlate with whole url/domain tracking and if those happens then uBO should deny it.
ATM I can remember only IMDB, where it kicks-in.

Can I take a few days/a week or so before final answer, please? I would like to see what will be collected in the logs in the mean time.

Wish you best

**Comment by bitpixl** [comment]
Take as much time as you need! :)

**Comment by bitpixl** [comment]
Just an update, I've also switched to ClearURLs, seems to be working fine.

Closing this ticket ;)

**Comment by crssi** [comment]
I have never forgotten about this.
ClearURLs also seems to be "abandoned"... at least I do not see any serious activity.
I still don't like ClearURLs, but haven't found better alternative, but really had rarely problems with it.

**Comment by bitpixl** [comment]
You sure about that? On gitlab and github the project seems to be alive? last updates being 3 weeks ago.

**Comment by crssi** [comment]
@bitpixl 
Just hit another CleanURL breakage and I am wonder are you using NeatURL or CleanURL?

**Comment by bitpixl** [comment]
test reply because i've been unable to

**Comment by bitpixl** [comment]
test reply 2 with user.js added... because i was unable to

**Comment by bitpixl** [comment]
test reply #3 with user.js added... because i was unable to... (sorry crssi)

**Comment by bitpixl** [comment]
update: right... sorry for spamming you @crssi ... (hope all is well) Was losing my mind why I was unable to answer on github. turns out something changed with the cookies and my cookieautodelete settings were too restrictive. Anyways, go that solved 👍 

About CleanURL vs NeatURL, I hope/think you mean ClearURLs ;) right now I'm (still) using ClearURLs and I haven't ran into any issues with it so far. I hope the breakage on you end wasn't anything too serious? I do like (like you do) that ClearURLs is set and forget, however, that's also it's downfall for when things go wrong...

Have you switched back? Put in a ticket?

**Comment by crssi** [comment]
Thank you...

Yes, I have opened a ticket there `https://gitlab.com/anti-tracking/ClearURLs/rules/-/issues/179`, but I still think that there things go very very slow, if at all. 😉

**Comment by bitpixl** [comment]
I'm sorry about that, I will never use your github as testing ground again! (crosses two fingers behind back) ;)

It seems for both addons the tickets are piling up atm, but at least development for ClearURLs is still going, where the last update for NeatURL was 15 months ago... not a good sign...

**Comment by crssi** [comment]
> I'm sorry about that, I will never use your github as testing ground again! (crosses two fingers behind back) ;)

That is not a problem. 😉 

> It seems for both addons the tickets are piling up atm, but at least development for ClearURLs is still going, where the last update for NeatURL was 15 months ago... not a good sign...

I do not see a problem with NeatURL since:
1. The extension is stable and working as intended, so no update is needed since nothing is broken
2.  We have control on rules part

As for ClearURLs we dont have a simple way to make inclusion/exclusions. The only way to overcome some problems on rules part is, or to humbly wait that the ticket will be processed (which happen with great delay or never), or to fork the rules part.

OFC nether one is ideal.
